/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class serialize_YAML */

#ifndef _Included_serialize_YAML
#define _Included_serialize_YAML
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     serialize_YAML
 * Method:    serialize_schema
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_serialize_YAML_serialize_1schema
  (JNIEnv *, jclass, jobject);

/*
 * Class:     serialize_YAML
 * Method:    serialize_schema_name
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_serialize_YAML_serialize_1schema_1name
  (JNIEnv *, jclass, jobject);

/*
 * Class:     serialize_YAML
 * Method:    serialize_table_cols
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_serialize_YAML_serialize_1table_1cols
  (JNIEnv *, jclass, jobject);

/*
 * Class:     serialize_YAML
 * Method:    serialize_tables_table
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_serialize_YAML_serialize_1tables_1table
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
